### ISSUE TITLE
Mail out prizes from Code Rush 2

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#1022]
- [x] Sticker to Casey Miller
- [ ] Sticker to Yujia Pan
- [ ] Sticker and t-shirt to Tara A.

**Comment by palewire** [comment]
We can handle most of this at #NICAR16, I think.

**Comment by caseymm** [comment]
:raised_hands:

**Comment by palewire** [comment]
I packed your sticker!
