### ISSUE TITLE
Cache our dependencies on TravisCI to speed tests

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#103]
I assume we'll have to switch to their [container service](http://docs.travis-ci.com/user/workers/container-based-infrastructure/) and use the [cache option](http://docs.travis-ci.com/user/workers/container-based-infrastructure/) that provides.

**Comment by palewire** [comment]
[Here's what it took](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/.travis.yml#L21) to make the magic happen in the new version of pip.

**Comment by Charlex** [comment]
Woah. That's left field. How'd you figure that out?

--
H. Charley Bodkin
Sent from my phone
301-221-4119

**Comment by palewire** [comment]
I read [the documentation](https://pip.pypa.io/en/latest/reference/pip_install.html#caching)

**Comment by Charlex** [comment]
Ah, pip's inbuilt caching! I had just focused on Travis config!
