### ISSUE TITLE
Where do "intermediary" contributions and their earmarked metadata surface in the database?

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#1164]
We can see them visible in filings, like Charles Munger's major donor sheets, but can we find them all in the database http://cal-access.ss.ca.gov/PDFGen/pdfgen.prg?filingid=1980975&amendid=0

![screenshot - 01082016 - 01 07 11 pm](https://cloud.githubusercontent.com/assets/9993/12209587/e5f83924-b608-11e5-9ffb-5b5c50d03f2d.png)

**Comment by gordonje** [comment]
Looks like we can!
```sql
select *
from "TEXT_MEMO_CD"
where "TEXT4000" like '%MADE THROUGH INTERMEDIARY CALIFORNIA REPUBLICAN LEADERSHIP FUND (#1340317); 455 CAPITOL MALL, SUITE 600, SACRAMENTO,%'
and "FILING_ID" = 1980975;
```

**Comment by palewire** [comment]
Interesting thing. There's probably some way to ultimately surface all
these "pass throughs" in one place, though I don't think it should jump the
line of the higher priority models we've got on tap.
