### ISSUE TITLE
Docstrings for all models in the database

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#1176]
Among the 76 database tables in the CAL-ACCESS system there are a number undocumented by the state that we do not understand. Here is the running list. 

You can help our effort by choosing one, researching its use inside the system, ferreting out any documentation we may have missed, and patching the codebase with a docstrings on its model and fields. 

- [ ] LobbyingChgLogCd
- [ ] FilerStatusTypesCd
- [ ] LobbyistEmployer1Cd
- [ ] LobbyistEmployer2Cd
- [ ] LobbyistEmployer3Cd
- [ ] LobbyistEmployerFirms1Cd
- [ ] LobbyistEmployerFirms2Cd
- [ ] LobbyistEmpLobbyist1Cd
- [ ] LobbyistEmpLobbyist2Cd
- [ ] LobbyistFirm1Cd
- [ ] LobbyistFirm2Cd
- [ ] LobbyistFirm3Cd
- [ ] LobbyistFirmEmployer1Cd
- [ ] LobbyistFirmEmployer2Cd
- [ ] LobbyistFirmLobbyist1Cd
- [ ] LobbyistFirmLobbyist2Cd
- [ ] ReportsCd
- [ ] EfsFilingLogCd
- [ ] ReceivedFilingsCd

**Comment by aboutaaron** [comment]
Documentation: http://www.documentcloud.org/documents/1308002-cal-access-about.html#document/p100
