### ISSUE TITLE
Add app_name option to downloadcalaccessrawdata

### ISSUE THREAD

**Issue by gordonje** [california-civic-data-coalition/django-calaccess-raw-data#1178]
(Arose out of work on #1169)

The `downloadcalaccessrawdata` command has a global `download_file()` function that's called by one of the command's `.download` method. I'm wondering why the global function is necessary: Why not just move all this logic inside `.download`? 

It doesn't appear as though the global function is being called anywhere else in calaccess_raw's code.

Looks like this was added as part of implementing the resume-download option (#1154)  because other apps need to be able to use this logic. 

Seems like we did something similar when we implemented an `--app-name` option for loadcalaccessrawfile (see #1145). 

Maybe the download command needs the `--app-name` option as well, then we could move this logic back inside the command's method.

**Comment by palewire** [comment]
If I understand you right, I agree that it makes more sense to have it attached to the class than just floating at the top of the file.

**Comment by palewire** [comment]
Here's an idea: What if that ["download_file"](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/management/commands/downloadcalaccessrawdata.py#L29-L57) function at the top of this command was abstracted back into our base [CalAccessCommand](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/management/commands/__init__.py) so it could accessed from any of our existing commands, any subclasses and also added as a mixin to anything else in the future?
