### ISSUE TITLE
Expand verifycalaccessrawfile and other commands to analyze the extent of the missing records

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#1189]
- [ ] Calculate and report the percentage of the table that missing
- [ ] Loop through all tables to calculate the percentage of the entire database that is missing
- [ ] Provide a more straightforward notification to the user during clean of what's been subtracted
- [ ] Add a FAQ answer to describe the extent of the data being lost during cleaning and explain why its being lost

**Comment by gordonje** [comment]
Are we thinking that verifying all the tables should be part of `updatecalaccessrawdata`? I kinda like that, given how we currently have things set up. And I think users will appreciate these reports as much as we will, so why not give it to them by default.

A little concerned about how long it will take to verify all tables, but we can't know until we try it first. Of course we could add a `--skip-verify` option. And maybe we only want to do it if the user opts for a higher verbosity level.

**Comment by palewire** [comment]
I think that could work. Maybe a report card at the end of the report based on what the commands return, which could include something like:

- [ ] Total number of tables loaded
- [ ] Total number of records loaded
- [ ] Count and percentage of records discarded during cleaning
- [ ] A list of which tables lost records and how many

**Comment by palewire** [comment]
Could it also check if any TSVs are in the ZIP but not loaded

**Comment by gordonje** [comment]
@palewire / @aboutaaron: How do we feel about moving toward logging this info in our database? I think the benefits are:

1.    Speed (we can stash record counts as we go without having to iterate through files multiple times);
2.    Easier calculating of totals and percentages;
3.    Less reliant on all the keeping files;
4.    It's big step toward future requirements for archiving and tracking of changes to the source data.

The only reason I can think to not do it is that it really locks the user into having MySQL or PostgreSQL up and running, whereas before they might have been able to get around that by never using the load command.

**Comment by palewire** [comment]
I have mixed feelings on it. 

On one hand, I'm reluctant to add complexity at this layer of the stack we don't absolutely need. It's more code to write and support, which means less time for other things.

On the other hand, I can see how introducing the complexity of the database might make the code less complex in some ways that could be better on net.

How would you propose the database be structured?

**Comment by gordonje** [comment]
There would one SourceFiles table with a record for each data file found in the downloaded .zip files data directory. Columns would be:
*    file_name (e.g., 'FILER_FILINGS.TSV')
*    datetime_download (what we currently stored in .last_download)
*    row_count (number of lines minus 1 for the header)
*    cleaned_row_count (number of rows, minus header, in the csv file)
*    loaded_row_count (number of records in the data table)

If we wanted to take it a step further, we could add another table with a record representing each version of the CAL-ACCESS source .zip file, which would be referenced by the SourceFiles table. But we can also just group by the datetime_download for now. (Some of this feels a little like the functionality we might want to reserve for the download site).

If we would rather hold off on introducing logging in the db, then I'm thinking I'll create a new command that borrows from verify, but iterates through multiple files / models at once, then spits out a report via template. Which seems to be close to the original proposal.

**Comment by gordonje** [comment]
But the non-db approach will only work if the user has opted to keep files. Otherwise, we'll need a way to keep track of record counts in the deleted files. I can sort of imagine a scheme relying on simple text files, but at that point, I'm really just hankering for a db.

**Comment by palewire** [comment]
Seems plausible to me, though if we go in on this I think we should take the extra step of adding a second table for each download run.

How would the ``--resume`` functionality work with this?

**Comment by gordonje** [comment]
We'll probably go ahead and replace the .lastdownload file, in which case the `--resume` option will instead query the downloads table, looking for a record based on the date-modified in the response header.

The first draft I'm doing right not will not rely on any db backend, but I think might lay the groundwork for that. At the very least, it will help us iron out exactly what we want to store and where we might need to optimize.

**Comment by palewire** [comment]
Alrighty. Boldly go.

**Comment by aboutaaron** [comment]
Seems like y'all have a plan, but I, too, like the idea of logging the `updatecalaccessrawdata` results into a table. For one, I think this will provide great data on how much work we need to go through to clean up a government dataset. Also, it'll be nice to know what's missing as we get closer to the election.

**Comment by gordonje** [comment]
We all agree now that we're ready to take this on. I'm going to finish this draft so that we'll have a basic report to start looking at, then pivot to using the db to archive this info and start incorporating it into our coverage reports and docs.

**Comment by palewire** [comment]
![do it](https://media.giphy.com/media/ACcXRXwUqJ6Ok/giphy.gif)

**Comment by palewire** [comment]
Note: Remember to add documentation on the new tracking models to our main docs site.

**Comment by palewire** [comment]
Admins, too.
