### ISSUE TITLE
ENTY_NAMT too long for char(9) in Cvr2SoCd table

### ISSUE THREAD

**Issue by jsfenfen** [california-civic-data-coalition/django-calaccess-raw-data#1198]
The download of Cvr2SoCd as of now includes "Vice Chair" as an entry in ENTY_NAMT ar row 36559 or so. It's the only time that field exceeds 9 chars, but that's enough to break the postgres load.

**Comment by palewire** [comment]
Good catch @jsfenfen! I wonder how many other fields are looming problems like this.
