### ISSUE TITLE
Variable length character field settings on the models that don't match the docs

### ISSUE THREAD

**Issue by jsfenfen** [california-civic-data-coalition/django-calaccess-raw-data#1199]
After #1198 I took a look at some nearby fields and noticed a few more that don't match the docs [here](http://www.documentcloud.org/documents/1308002-cal-access-about.html#document/p46) (I think the states CVR_2S0 is the same table as Cvr2SoCd) . Specifically, [enty_naml](http://www.documentcloud.org/documents/1308002-cal-access-about.html#document/p46) which is 194 in the django model and 200 in the docs, and [enty_namf,](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/models/campaign.py#L477) which is 34 in the django model and 45 in the docs. It's pretty unlikely that any one of these is gonna be a problem immediately, but it does seem like the sorta thing that may occasionally be a pain. 

I'm guessing the original models were written before the docs were available by just looking at the maximum size of a current dump. And not all the fields listed in the docs actually have max sizes (that I can figure out, anyways). But it would probably be possible to parse out lotsa them. One question, though--is 'cd' always appended, or does it signify something I might be missing?

**Comment by palewire** [comment]
I think that your theory on the field lengths is probably right, though the memory of how it was done might rest with @armendariz. I suppose we probably need to do a run through all the fields in the database and increase the size of any where the documentation is higher than what we have to avoid the error you patched earlier in the day for #1198.

As far the ``Cd`` suffix on tables, that is there because the same string is appended to every text file in the ZIP file source data. I could see a case for removing something to redundant. When it was drafted I was simply trying to hew as closely as possible to the source data.

**Comment by jsfenfen** [comment]
Ah, I get it about the 'cd'. I just wanted to make sure I knew how to translate table names... 

FWIW [ind_group](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/models/campaign.py#L547) (length 87) also doesn't match. 

I could probably hack something up to do the comparison between the docs and the models, though if there's institutional memory about what's already been cleaned up (and maybe this one table was just missed) it might not be worth doing.

**Comment by armendariz** [comment]
It's probably worth hacking something up to compare the docs to the models.
MySQL throws a ton of truncation errors that I intentionally ignored as I
tried to figure out how it all fit together and what I actually cared about
in there.

**Comment by gordonje** [comment]
That sounds awesome @jsfenfen. Should we also stop ignoring these warnings [here](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/management/commands/loadcalaccessrawfile.py#L140)?

Alternatively (or perhaps as well?), I've been wondering if we should add some checks to `cleancalaccessrawfile`. When we iterate over each line in the .CSV, we could go read these into model instances and then call [.clean_fields()](https://docs.djangoproject.com/en/1.9/ref/models/instances/#django.db.models.Model.clean_fields) to see if we get any validation errors. I assume this would be less overhead than actual trying to save the records because it would avoid hitting the db.

**Comment by bcipolli** [comment]
Is there a performance concern? I wonder if saving individual models, and making individual error reports, would be fine for this application?

In that case, you can also shove the csv line into an "errors" table, that can be re-run once the issue has been debugged & fixed. We did this for https://github.com/learningequality/ka-lite , and it seemed to work well.

Could be too much complexity here, just an idea..

**Comment by palewire** [comment]
It's definetely a performance concern, but I can't say we've tested what exactly the hit would be. My gut says it would slow things down considerably, but I could very well be wrong. 

If it could become part of a general "resilience" framework of change that included things like the error handling you describe, I could see some value. 

However, due to the very very low percentage of errors in the overall database, I'm torn and undecided about whether a better investment of time on the "clean" step might be to move the other direction. By that I mean pursuing a "speed" agenda that would try to replace Python-level operations that require looping through the records with attempt lower-level shell operations that handle the same tasks.

**Comment by armendariz** [comment]
I'd heed Ben's speed concerns. I had lots of checking and really slow code
to start with that Ben sped up exponentially and it was a very good thing
he did.

It's been a while but I believe the error rate was so low that it didn't
matter to me. And every time I dug into the database I never noticed any
blatant ones.

**Comment by bcipolli** [comment]
>My gut says it would slow things down considerably, but I could very well be wrong.

It will slow things down. My point is only that, in production, performance is not a concern, is it? As long as the process completes daily, does it matter if it takes 5 minutes or 500 minutes?

>I'd heed Ben's speed concerns.

I'm also Ben ;) But I'm all for speed, if it's a need. :)

**Comment by armendariz** [comment]
Ha! So much for my ability to read. Hi Ben I don't know! Sorry about that.

When a filing deadline hits processing speed will matter a lot

**Comment by palewire** [comment]
@bcipolli: Our newsroom use case prioritizes speed very highly. We want to be able to review and analyze the freshest data as soon as possible. However, I recognize that some other use cases, like slow-speed research or website development might not rank it has highly.

**Comment by gordonje** [comment]
I tried removing these the [MySQL warnings filters](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/management/commands/loadcalaccessrawfile.py#L138-L140) from the load command, but was still not getting any errors. Seems like MySQL will just always quietly truncate the data.

**Comment by palewire** [comment]
Interesting. This is speculative, but it's also possible there is some lower level MySQL option that controls that sort of thing.

**Comment by jsfenfen** [comment]
Ok, I ran the dox vs whats in the django models for fields that I could match and that had maxlengths. These are the places where the django maxlength was * less * than the cal access dox maxlengths (and the reference page in the documentation). I may have messed this up, please lemme know. Fwiw here are the calaccess_raw[ field lengths](https://gist.github.com/jsfenfen/93afa9997f178ec6b0f2) and those I [parsed](https://gist.github.com/jsfenfen/21d6bce2ea5449f20137) from the [docs](http://www.documentcloud.org/documents/1308002-cal-access-about.html) (by looking at p. 14-98ish). 

CVR2_SO.ENTY_NAML django:194 - dox: 200 see p. 46
CVR2_SO.ENTY_NAMF django:34 - dox: 45 see p. 46
CVR2_SO.ENTY_NAMT django:9 - dox: 10 see p. 46
CVR2_SO.MAIL_CITY django:25 - dox: 30 see p. 47
CVR2_SO.EMAIL_ADR django:40 - dox: 60 see p. 47
CVR2_SO.IND_GROUP django:87 - dox: 90 see p. 47
CVR2_SO.PARTY_NAME django:63 - dox: 200 see p. 48
CVR2_SO.POF_TITLE django:44 - dox: 45 see p. 47
CVR3_VERIFICATION_INFO.SIG_LOC django:39 - dox: 45 see p. 49
CVR3_VERIFICATION_INFO.SIG_NAML django:56 - dox: 200 see p. 49
CVR3_VERIFICATION_INFO.SIG_NAMS django:8 - dox: 10 see p. 50
CVR_REGISTRATION.FILER_ID django:8 - dox: 9 see p. 30
CVR_LOBBY_DISCLOSURE.FILER_ID django:8 - dox: 9 see p. 25
LOBBY_AMENDMENTS.D_L_NAML django:56 - dox: 200 see p. 73
LOBBY_AMENDMENTS.D_L_NAMF django:35 - dox: 45 see p. 73
LOBBY_AMENDMENTS.D_L_NAMS django:8 - dox: 10 see p. 73
LOBBY_AMENDMENTS.D_LE_NAML django:160 - dox: 200 see p. 73
LOBBY_AMENDMENTS.D_LE_NAMS django:9 - dox: 10 see p. 74
LCCM.CTRIB_NAML django:120 - dox: 200 see p. 63

I think there were 184 fields I couldn't match (stuff that's in the django but not in the dox), I haven't really looked at that. The only text munging I did was to remove the _CD from the db_table names.

**Comment by jsfenfen** [comment]
Also, fwiw, the keys I couldn't match [are here](https://gist.github.com/jsfenfen/f5c95896e37b2e916d0d). What's listed are [db table name].[field name] that I couldn't find in the documentation, either because they weren't listed in the part of the dox I was parsing or because there's some name munging that I did wrong or something else entirely. Suffice it to say I couldn't check them.

**Comment by jsfenfen** [comment]
Ahh, I see, most if not all of the ones I couldn't find are in fact documented in a *later section of the documentation document* i.e. around page, around page 155 for table F501_502. Sigh.

**Comment by jsfenfen** [comment]
Hey so I double checked both parts of the cal access documentation, and all the fields that were too short in my parse of the *first part* of the dox are also too long in the *second part* of the dox. Comfortingly all the fields I looked at were identical, btw. Unless there's a good reason not to I'm gonna submit a PR with the model field changes...

**Comment by gordonje** [comment]
@jsfenfen Thanks so much for looking into this. Go ahead with the PR.

Were you parsing the docs in Python? If you're willing to share that code, maybe we could find a home for it in this repo (or a related one). Might be helpful as we get deeper into documentation.

**Comment by jsfenfen** [comment]
@gordonje yeah I am parsing using python, but am doing so using a combination of [pdfplumber](https://github.com/jsvine/pdfplumber/) and a [util](https://github.com/jsfenfen/pdf_bbox_utils/blob/master/coalesce_words.py) I have to turn chars into words. It's repeatable (and I can dump it in a gist or something) but you wouldn't want the dependencies.

**Comment by gordonje** [comment]
Got it. Yeah, I gist would be fine. Then I could refer to it as a resource for some of the other tasks we have in the works.

**Comment by palewire** [comment]
You think you got them all? Or are there more?

**Comment by jsfenfen** [comment]
So I think I got the ones that are mentioned in the first half of the documentation--roughly page 14-98. I didn't realize this initially, but some tables only appear in the second part of the documentation (p. 99-234 I think).

To be honest, I didn't realize the two parts include different tables. One's dated april of 2002 and the other is feb. 2002--have no idea what that signifies though. 

There were about 175 I couldn't check outta 980-ish total fields. I'll likely hack something up to check the second part of the documentation as well. It seems like most of the errors were clustered in a few tables so that might be all of them.

**Comment by gordonje** [comment]
I just happened to be in the docs near this table, so I took care of this one.

**Comment by palewire** [comment]
So have all these been corrected?
