### ISSUE TITLE
Add docstring for FilerEthicsCd model

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#120]
* [Model](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/models/other.py#L133)
* [Docs](http://www.documentcloud.org/documents/1308002-cal-access-about.html#document/p107)

**Comment by mhkeller** [comment]
I got this.

**Comment by mhkeller** [comment]
@palewire is this the same as https://github.com/california-civic-data-coalition/django-calaccess-raw-data/issues/119?

I don't see a FilerEthicsCd model either, just FilerEthicsClassCd https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/models/other.py#L125

**Comment by mhkeller** [comment]
Doc screenshot ![screen shot 2015-03-05 at 14 55 33 pm](https://cloud.githubusercontent.com/assets/498744/6513279/dd835b48-c347-11e4-97f8-90d105b62011.png)
