### ISSUE TITLE
Investigate why some database tables end up with more clean records than downloaded records

### ISSUE THREAD

**Issue by gordonje** [california-civic-data-coalition/django-calaccess-raw-data#1200]
For the following files, the count of clean records is inexplicably greater than the count of download records.

| File_Name    | Download_Count | Clean_Count | Load_Count |
| ------------ | --------------:| -----------:| ----------:|
| RCPT_CD      |        9271635 |     9281001 |    9271634 |
| EXPN_CD      |        4797362 |     4799460 |    4797361 |
| DEBT_CD      |         409235 |      409614 |     409234 |
| SPLT_CD      |        3168645 |     3174202 |    3168644 |
| TEXT_MEMO_CD |        1522585 |     1522602 |    1522584 |

**Comment by palewire** [comment]
One thing that most of those have in common is that they contain schedule line-items, like contributions and expenditures.

**Comment by gordonje** [comment]
Some clean up left on this one, but at least the numbers are correct now. Seems like some extra carriage return chars are sneaking in somewhere in the writing of the clean files.
