### ISSUE TITLE
Enhanced Resume behavior

### ISSUE THREAD

**Issue by gordonje** [california-civic-data-coalition/django-calaccess-raw-data#1202]
Once the tracking models are in place, we'll have the foundation for the following improvements:

*    The update and download commands should automatically check if their previous job did not complete and offer the user to finish (i.e., we won't need the `--resume` option anymore).
*    User should have the ability to opt out of resuming and the option to start over.
*    Since we have a `--no-input` option which skips the prompts, we might want to add a `--force-restart` option.
*    Note that a download can only be resumed if the version for the incomplete download is the same as the version currently available at the CAL-ACCESS url. If this scenario arises, we should probably notify the user that their previous download cannot be completed and give them the option to update to the currently available version.
*    The update command should be able to check which files it has cleaned and which it has loaded. It should be able to resume cleaning / loading for any files that do not have CalAccessCommandLog with finish_datetime values for the given update.

**Comment by gordonje** [comment]
A rather specific use case arose for me today that I wanted to throw out for the group to consider.

If a user starts downloading a specific version by calling `downloadcalaccessrawdata`, gets interrupted and doesn't complete that download, then later goes back and calls `updatecalaccessrawdata` while the version previously being downloaded is still available, should we resume the download or start a new one?

I'm inclined to resume the download, even though it wasn't initiated by an instruction to update the database. This preference is based on the assumption that, for the user, there's no significant difference between a download they kickstart on their own and one that happens as part of the full update.

If we go that route, then there are two implications in terms of the CalAccessCommandLog records:

1.    We should then link this download up with the update command which resumed it (i.e., set the download's CalAccessCommandLog.called_by field to the id of the update's CalAccessCommandLog record); or    
2.    The resumed download should remain unlinked from the update command that resumes it (i.e., we leave the update's CalAccessCommandLog.called_by field NULL.

I'm inclined to go with 2. To me, there's no obvious reason why each update needs to have each kind of sub-command linked back to it. Actually, as long as we maintain the `--skip...` options, there are likely to be plenty of times when updates have some, but not all of the sub-commands.

Probably the deciding factor here is to do whatever is necessary to publish the reports and feedback that make sense for the users.

**Comment by gordonje** [comment]
About those `--skip-...` options...

It's worth considering how useful they will be after we implement the auto-resume behavior described above. I think the primary use case before was "I've already download and/or cleaned, so this time I want to skip that." The expectations is that this will happen for them automatically, without invoking the `--skip-...` options.

The one use case I can think of the still makes some sense is "I want to download and clean the files, but (for whatever reason) I don't want to load yet." That's probably a good enough reason to maintain them.

**Comment by palewire** [comment]
I believe this has landed.
