### ISSUE TITLE
Surface DOCUMENTCLOUD_PAGE_URLS links in automatically generated model documentation

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#1203]
It would be cool if they could appear as little thumbnail images you could click on to open up.

**Comment by palewire** [comment]
something like adding it here http://django-calaccess-raw-data.californiacivicdata.org/en/latest/models.html

**Comment by gordonje** [comment]
Seems [DocumentCloud thumbnails](https://blog.documentcloud.org/blog/2010/10/how-to-grab-thumbnail-images/) require the doc's title (e.g., "Cal-Readme", "FAQ", "CalAccessTablesWeb") in addition to the document id and page number. 

So we might need to add that to the [DocumentCloud class](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/models/base.py#L135) and pass it in from the model attribute like so:
```python
    DOCUMENTCLOUD_PAGES = [
        DocumentCloud(id=2711615, title="FAQ", start_page=2, end_page=2)
    ]
```

Seems a little redundant, but does add some readability to this attr (who is going to remember which doc_id's correspond to which docs?)

Or we could request it from the DocumentCloud API, which includes the thumbnail and other resources in their [json response](https://www.documentcloud.org/documents/2712034-FAQ.json).

**Comment by gordonje** [comment]
I went with getting the id (with title) from the DocumentCloud GET method. I stuck with our current approach of hard-coding the URL pattern, but as the API evolves, we might consider just using URLS in the results of this request.

For now just including each models thumbnails all under a single heading, no labeling. Might be nicer if we group all the pages for a given doc together under the doc's title. But not sure right now how we want all this to look.

**Comment by gordonje** [comment]
Oh, also noted travis throws "nonlocal image URI found" for all the thumbnail urls. Not sure that really matters but, if it does, we could instead download the .gifs as part of creating the automated doc generation.

**Comment by palewire** [comment]
Am I reading it that has is done for the models and but not the choices fields?

**Comment by palewire** [comment]
Yes, this done for the models not the fields.
