### ISSUE TITLE
Figure out what kind of documentcloud URLs are best to go in our new model and field settings?

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#1205]
Should it be full urls to pages with anchor links in the standard doccloud viewer? Should it be JPG urls? Either way, it might be nice to have a model method than can convert the two, or return an page embed or something.

**Comment by reefdog** [comment]
We'd like to [use pushState more aggressively on the document viewer](https://github.com/documentcloud/documentcloud/issues/317) so that URLs like https://www.documentcloud.org/documents/282753-lefler-thesis/pages/57.html will have similar behavior to (and supercede) page anchor links like https://www.documentcloud.org/documents/282753-lefler-thesis.html#document/p57.

Don't have a timeline, but wanted you to be aware of our future plans in case it affects yours.

**Comment by palewire** [comment]
Thanks for the info. Let's live on the bleeding edge!

**Comment by gordonje** [comment]
Wondering if, instead of urls, it would make more sense if the model attr was a list of dicts like this:

```python
DOCUMENTCLOUD_PAGES = [
    {'doc_id': 1308000, 'start_page': 101},
    {'doc_id': 1308002, 'start_page': 216, 'end_page': 219},
]
```
And then we could have methods to generate whatever urls we need, including multiple ones for each page in a range if we need that.

**Comment by palewire** [comment]
That's definitely a more structured approach. It will require more training and knowledge by contributors. Not sure where I come down on striking that balance between easy-to-paste and easy-to-parse. What do y'all other nerds think?

**Comment by palewire** [comment]
I took a stab at implementing @gordonje's idea tonight and here's what I can up with. 

* [The base model attribute](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/models/base.py#L35-L42) is renamed ``DOCUMENTCLOUD_PAGES``
* There is a new [``DocumentCloud``](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/models/base.py#L135-L164) class that will create page range objects similar to the ones he outlined
* I filled in a couple of them for the ``CvrSoCd` model on both [the model itself](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/models/campaign.py#L23-L30) as well as [one of the choices fields](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/models/campaign.py#L222-L235)
* I added [model methods](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/models/base.py#L118-L129) on the base classes that will spit out the new style DocumentCloud URLs as outlined by @reefdog

The result is that an instance of that model can now spit out combined ranges of URLS, like so.

```python
>>> from calaccess_raw.models import CvrSoCd
>>> CvrSoCd().get_documentcloud_page_urls()
[u'https://www.documentcloud.org/documents/1308004/pages/3.html', u'https://www.documentcloud.org/documents/1308004/pages/4.html', u'https://www.documentcloud.org/documents/1308004/pages/5.html', u'https://www.documentcloud.org/documents/1308004/pages/6.html', u'https://www.documentcloud.org/documents/1308004/pages/7.html', u'https://www.documentcloud.org/documents/1308004/pages/21.html', u'https://www.documentcloud.org/documents/1308004/pages/22.html', u'https://www.documentcloud.org/documents/1308004/pages/25.html', u'https://www.documentcloud.org/documents/1308004/pages/26.html', u'https://www.documentcloud.org/documents/1308004/pages/27.html', u'https://www.documentcloud.org/documents/1308004/pages/28.html', u'https://www.documentcloud.org/documents/1308004/pages/29.html', u'https://www.documentcloud.org/documents/1308004/pages/30.html', u'https://www.documentcloud.org/documents/1308004/pages/31.html']
```

What do you think? Like it?

**Comment by gordonje** [comment]
![excited_charlie](https://cloud.githubusercontent.com/assets/4304548/13010742/10f35908-d169-11e5-901c-db657a1fb2e6.gif)

**Comment by palewire** [comment]
I guess we have a decision. Now we just have to live up to it.
