### ISSUE TITLE
Add Django FileFields to the tracking models and refactor to save the ZIP and TSV/CSVs as they are loaded

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#1206]
For a start, let's just use the local disk default MEDIA settings. But if this works, we can try to snap in an Amazon S3 backend blah blah

**Comment by palewire** [comment]
https://docs.djangoproject.com/es/1.9/ref/models/fields/#filefield

**Comment by palewire** [comment]
https://django-storages.readthedocs.org/en/latest/

**Comment by palewire** [comment]
https://github.com/juliomalegria/django-chunked-upload

**Comment by anthonyjpesce** [comment]
I'll grab

**Comment by gordonje** [comment]
Done! Thanks a million @anthonyjpesce!

**Comment by anthonyjpesce** [comment]
Woo!

**Comment by palewire** [comment]
![](https://media.giphy.com/media/IZ7RuI6OWSFtC/giphy.gif)
