### ISSUE TITLE
Pool the LOAD DATA INFILE and COPY commands to speed up loading

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#1213]
@schwanksta seems to have pulled it off here

https://gist.github.com/Schwanksta/d86189e3ace312372113

**Comment by Schwanksta** [comment]
In the end I'm not 100% sure it was faster. will test a little more.

**Comment by Schwanksta** [comment]
Vacuumed the db and re-ran it using cpu_count()/2 on a set of 25 ~191mb files totaling 4.7gb. They loaded at about 5/min, or almost a gb per minute. Not bad. I think maxing out the cores, which I tried first, actually slows it down somewhat.

**Comment by palewire** [comment]
Very interesting. We'll have to test it on here.

**Comment by emilbayes** [comment]
Regarding cores being maxed out: I've experienced this before when importing huge datasets, and as the [documentation notes](https://wiki.postgresql.org/wiki/COPY) the `COPY` command might become the bottleneck itself. If this is really important to the project, you might want to consider writing a custom driver for the binary copy protocol. I did that for a Node.js crawler project to get the last bit of performance, and saw a substantial increase or ~ 5 - 10% IIRC. However what really sped up import was tuning the database configuration as noted in the ["Populating a Database" article](http://www.postgresql.org/docs/current/interactive/populate.html) of the Postgres documentation. In particular the following:

```ini
maintenance_work_mem = 1024 # something large, in MB
checkpoint_segments = 24 # Defers write ahead log (WAL) to 24 segments, the default is 3
checkpoint_timeout = 3600 # Wall clock time between committing to the WAL
synchronous_commit = off # Makes transactions more uncertain, but doesn't matter for import
autovacuum = false # Disable autovacuum while importing, and do it at the end of transactions manually
```

However, modifying the config during import is not something I know if is doable.

Another useful source is [`pg_bulkload`s parallel writer](https://github.com/ossc-db/pg_bulkload/blob/master/lib/writer_parallel.c), though it's a bit opaque, unless you spend some time understanding how it implements Readers and Writers.

**Comment by palewire** [comment]
Just for a little bit of rough benchmarking, here are the time stamps from my work tower when I ran an update earlier today. Both the clean and load take a long time, but the load takes a little longer for me.

```bash
Downloading ZIP file
[################################] 754760/754760 - 00:06:37
 Unzipping archive
 Prepping unzipped data
 Archiving original files
Duration: 0:07:44.365715
Cleaning data files
[################################] 80/80 - 00:23:02
Duration: 0:30:46.825341
Loading data files
[################################] 77/77 - 00:24:27
Duration: 0:55:14.623547
Done!
```

**Comment by palewire** [comment]
I just ran this locally with the pooling on with the same computer and it actually went slower!

```python
Downloading ZIP file
[################################] 737221/737221 - 00:01:06
 Unzipping archive
 Prepping unzipped data
 Archiving original files
Duration: 0:02:44.459307
Cleaning data files
Duration: 0:31:37.411594
Loading data files
Duration: 1:11:09.941578
Done!
```

Oddly, when I run the same code against our test files, it processes twice as fast with pooling as without. Here's my current half-baked theory: The small number of very large files (i.e. Rcpt and Smry) account for the vast majority of the processing time and are bogging down the clean and load pretty much the same amount no matter what order we load them in.
