### ISSUE TITLE
Add docstring to GroupTypesCd

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#127]
* [Model](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/models/other.py#L390)
* [Docs](http://www.documentcloud.org/documents/1308002-cal-access-about.html#document/p107)

**Comment by benlk** [comment]
Added by @tchristianmiller in #155, so this can be closed.
