### ISSUE TITLE
Add DocumentCloud references for MapCalFormat2Fields / campaign.py

### ISSUE THREAD

**Issue by amandabee** [california-civic-data-coalition/django-calaccess-raw-data#1283]
Placeholder, b/c Lindsay and I are working on this.

**Comment by gordonje** [comment]
Every model should now contain a DocumentCloud reference to pages in both CalAccessTablesWeb and MapCalFormat2Fields (or it is excluded from the test in test_docs.py).

**Comment by palewire** [comment]
![](https://media.giphy.com/media/lExXm1vSE7zb2/giphy.gif)
