### ISSUE TITLE
Add docstring for LobbyistEmpLobbyist1Cd

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#141]
* [Model](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/models/other.py#L768)
* [Docs](http://www.documentcloud.org/documents/1308002-cal-access-about.html#document/p107)

**Comment by chrisalcantara** [comment]
I'm on it!
