### ISSUE TITLE
Should we have a conda package?

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#1458]
I don't know. I am dumb, but I want to help.

**Comment by aboutaaron** [comment]
http://conda.pydata.org/docs/using/pkgs.html

**Comment by palewire** [comment]
well, I followed the newbie conda tutorial and it looks like their build tool is broken. here's [my bug report](https://github.com/conda/conda-build/issues/1089) on their end.
