### ISSUE TITLE
Add docstring for LobbyistFirmEmployer1Cd

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#146]
* [Model](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/models/other.py#L893)
* [Docs](http://www.documentcloud.org/documents/1308002-cal-access-about.html#document/p107)

**Comment by ryanvmenezes** [comment]
I got this
