### ISSUE TITLE
Output sample data for the name resolution service idea

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#1460]
The goal: Create a CSV with all the basic metadata we have candidates for office. What I can think of off the top of my head:

* Name
* Party
* Office sought
* Campaign cycles

**Comment by gordonje** [comment]
Here's a draft. Query and compressed .csv file are below.

I'm assuming a flatfile is the preferred format, and I've included the calaccess `FILER_ID` in case that will help with deduping these records.

For office, I'm using the `FILER_TO_FILER_TYPE_CDE.RACE` and excluding cases where the value of this field is NULL or 'N/A'.

For cycle, I'm using the `FILER_TO_FILER_TYPE_CDE.SESSION_ID` which seemed to be the handiest approximation. 

For any of these fields, I'm substituting NULL for the various ambiguous values (e.g., 'N/A' and 'UNKNOWN').

On the call, someone mentioned including contact info (address, phone, fax, email) for the candidates. This info is available directly on the `FILERNAME_CD` table as well as the `FILER_ADDRESS_CD` and `ADDRESS_CD` tables. It isn't clear to me, though, how we would pull out the current contact info for each candidate. And I'm hesitant to just throw these fields and multiply the records in this output. 

```SQL
SELECT DISTINCT
    fn."FILER_ID",
    REPLACE(
        TRIM(
            CONCAT("NAMT", ' ', "NAMF", ' ', "NAML", ' ', "NAMS")
        ),
        '  ',
        ' '
    ) as full_name,
    NULLIF(NULLIF(p."CODE_DESC", 'N/A'), 'UNKNOWN') as party,
    NULLIF(r."CODE_DESC", 'N/A') as office,
    NULLIF(d."CODE_DESC", 'N/A') as district,
    ft."SESSION_ID" as cycle
FROM "FILERNAME_CD" as fn
JOIN "FILER_TO_FILER_TYPE_CD" as ft
ON fn."FILER_ID" = ft."FILER_ID"
LEFT JOIN "LOOKUP_CODES_CD" as p
ON ft."PARTY_CD" = p."CODE_ID"
AND p."CODE_TYPE" = 16000
JOIN "LOOKUP_CODES_CD" as r
ON ft."RACE" = r."CODE_ID"
AND r."CODE_TYPE" IN (30000, 50000)
AND ft."RACE" <> 0
LEFT JOIN "LOOKUP_CODES_CD" as d
ON ft."DISTRICT_CD" = d."CODE_ID"
AND d."CODE_TYPE" = 17000
WHERE fn."FILER_TYPE" = 'CANDIDATE/OFFICEHOLDER'
ORDER BY fn."FILER_ID", ft."SESSION_ID" DESC
```
[candidates.csv.zip](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/files/243818/candidates.csv.zip)

**Comment by palewire** [comment]
This query looks like a great start, however for some reason Meg Whitman is not showing up which we'll need to sort out later. She sought the office of governor in the 2010 cycle and lost.

**Comment by gordonje** [comment]
Whitman is in the db (`FILER_ID = 1315466`), but is exclude from these results because her `FILER_TO_FILER_TYPE_CD.RACE` value is 0, meaning 'N/A'. This situation is the same for folks like Arianna Huffington(`FILER_ID = 1256558`) and Neel Kashkari (`FILER_ID = 1362979`). These are all people who have run, but have never been elected to any CA office. Possibly everyone who falls into that category is excluded from these results.

**Comment by gordonje** [comment]
I've got a new query (below) that solves this problem. Now I'm pulling all of this from the Form 501 "Candidate Intention" filing records, where the office field (among other things) is more consistently populated. These results should be distinct combos of:

* Candidate
* Office for which candidate was running
* Year of general election

I've also included the candidate contact info, which should be up-to-date as of the most recently amended version of the Form 501 filed by each candidate in each cycle.

```SQL
SELECT
    ff."FILER_ID",
    --names are not consistently parsed, so combine them for this output
    REPLACE(
        TRIM(
            CONCAT(ci."CAND_NAMT", ' ', ci."CAND_NAMF", ' ', ci."CAND_NAML", ' ', ci."CAND_NAMS")
        ),
        '  ',
        ' '
    ) as full_name,
    o."CODE_DESC" as office,
    d."CODE_DESC" as district,
    ci."AGENCY_NAM" as agency,
    p."CODE_DESC" as party,
    ci."YR_OF_ELEC" as election_year,
    ci."CAND_CITY" as city,
    ci."CAND_ST" as st,
    ci."CAND_ZIP4" as zip,
    ci."CAND_PHON" as phone,
    ci."CAND_FAX" as fax,
    ci."CAND_EMAIL" as email
FROM (
        --include only the most recent amendment to each filers Form 501 (Candidate Intention)
        SELECT "FILER_ID", "FILING_ID", MAX("FILING_SEQUENCE") as amend_id
        FROM "FILER_FILINGS_CD" 
        WHERE "FORM_ID" = 'F501'
        GROUP BY 1, 2
) as ff
JOIN "F501_502_CD" as ci
ON ff."FILING_ID" = ci."FILING_ID"
AND ff.amend_id = ci."AMEND_ID"
-- include office
JOIN "LOOKUP_CODES_CD" as o
ON ci."OFFICE_CD" = o."CODE_ID"
AND o."CODE_TYPE" IN (30000, 50000)
AND ci."OFFICE_CD" <> 0
-- include district
LEFT JOIN "LOOKUP_CODES_CD" as d
ON ci."DISTRICT_CD" = d."CODE_ID"
AND d."CODE_TYPE" = 17000
-- include party
LEFT JOIN "LOOKUP_CODES_CD" as p
ON ci."PARTY_CD" = p."CODE_ID"
AND p."CODE_TYPE" = 16000
ORDER BY ff."FILER_ID", ci."YR_OF_ELEC";
```
[candidates_v2.csv.zip](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/files/245759/candidates_v2.csv.zip)

**Comment by gordonje** [comment]
One thing that occurred to me with this round: Often the district is NULL or 'N/A' for local offices. In these cases, often the "agency" field populated with something like "City of...", which is why I have included it.

**Comment by palewire** [comment]
Looks like a great start!
