### ISSUE TITLE
Installing backend dependencies should be optional

### ISSUE THREAD

**Issue by adborden** [california-civic-data-coalition/django-calaccess-raw-data#1465]
We're using django-calaccess-raw-data with mysql, but `pip install django_calaccess_raw_data` dies when trying to install psycopg2 because `pg_config` isn't installed. It's quite cumbersome for us to have to install the mysql/postgres tools even though we're only using one of them.

**Comment by palewire** [comment]
Very good point and likely and oversight on our part. We didn't include psycopg2 in setup.py, but it might be a dependency of django-postgres-copy.

**Comment by palewire** [comment]
Yup. That's where it comes from. https://github.com/california-civic-data-coalition/django-postgres-copy/blob/master/setup.py#L47

**Comment by palewire** [comment]
We could remove the parent dependency here or the child one there. Not sure what the proper approach is, or if there's a third way.

**Comment by palewire** [comment]
@adborden, moments ago I released an updated version of our underlying dependency, django-postgres-copy, that no longer includes psycopg2 as a requirement. I believe that if you were to begin your installation again it would not longer try to install it and you would be able to continue without PostgreSQL.

**Comment by palewire** [comment]
I think we got this, so unless @adborden tells me otherwise I think this ticket can be closed.
