### ISSUE TITLE
Why is the test coverage score so high? That seems wrong.

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#215]

**Comment by palewire** [comment]
Big thing seems to be that it doesn't care if we miss methods on management commands.

**Comment by aboutaaron** [comment]
I keep seeing it fluctuate between 36% and 100% so I'm not entirely sure what's going on.

**Comment by palewire** [comment]
It's all fucked.

**Comment by palewire** [comment]
I just added a new test that loads in the sample data using a management command, which suddenly lead to that command's file being evaluated and our coverage score dropping. If I'm getting this right, it looks like you have to call those classes explicitly for coverage to consider them as part of the denominator.
