### ISSUE TITLE
Add help text to ExpnCd model

### ISSUE THREAD

**Issue by aboutaaron** [california-civic-data-coalition/django-calaccess-raw-data#222]
Similar to what we have on the RcptCd model

**Comment by aboutaaron** [comment]
Should we have choices for `expn_code`?

**Comment by aboutaaron** [comment]
`rec_type` value: EXPN
`sup_opp_cd` Support/Oppose? Values: S; O (F450, F461)

**Comment by palewire** [comment]
I'm in favor of the choices for anything that fits.
