### ISSUE TITLE
Integrate new test data set sample into unit tests

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#227]

**Comment by palewire** [comment]
Hey @ewr, I finally got your data in the unittests and up on TravisCI, which is surfacing a bunch of new interesting bugs. Thanks again!

**Comment by ewr** [comment]
![awesome](http://media0.giphy.com/media/MOWPkhRAUbR7i/giphy.gif)

Glad to hear it. I'd love to find a little time to circle back around and help out again.

**Comment by palewire** [comment]
Even if it's incomplete, whatever import script you wrote to that database visualization tool is worth getting in a gist or pull request or something

**Comment by ewr** [comment]
Sure:

https://github.com/ewr/es-import-tsv

**Comment by ewr** [comment]
And to add a little more context: That script writes the TSV into Elasticsearch. From there I was just using [Kibana](https://www.elastic.co/products/kibana) to play with visualization / exploration. 

You would probably be interested in this blog post if you didn't see it: 

https://www.elastic.co/blog/kibana-4-for-investigating-pacs-super-pacs-and-your-neighbors
