### ISSUE TITLE
prerequisites actually needed?

### ISSUE THREAD

**Issue by rkiddy** [california-civic-data-coalition/django-calaccess-raw-data#233]
I am starting to try to use this with a freshly installed Ubuntu 14.04 system. I am having problems with the prerequisites. Is pip not supposed to handle this?

When I run "python manage.py migrate", I am getting an error telling me that the libraries to access MySQL are not available. Full message below.

Has this been tested by, for example, running the configuration commands against a freshly created EC2 instance? If there are other prerequisites needed which are not set up by the commands given, what are they?

thanx - ray
```
$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/models.py", line 40, in <module>
    class Permission(models.Model):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 297, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 166, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/usr/local/lib/python2.7/dist-packages/django/db/__init__.py", line 40, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 242, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 108, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 18, in <module>
    raise ImproperlyConfigured("Error loading MySQLdb module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module: No module named MySQLdb
```

**Comment by palewire** [comment]
We do run tests against something like an empty EC2 instance using Travis Ci. You can see those tests [here](https://travis-ci.org/california-civic-data-coalition/django-calaccess-raw-data).

My reading of that error message is that you have not installed a Python wrapper for MySQL, like ``mysqlclient`` or ``python-mysql``, to allow Django link up with the database. 

It's possible that we just have a wire crossed somehow in our dependencies or installation instructions. Did you install the ``requirements_dev.txt`` file with pip, which appears to include [mysqlclient](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/requirements_dev.txt#L2)?

What was your installation routine? Did you follow the instructions [here](http://django-calaccess-raw-data.californiacivicdata.org/en/latest/howtocontribute.html)?

**Comment by rkiddy** [comment]
FYI, I needed to do both of these:

```
     apt-get install python-dev libmysqlclient-dev
     pip install MySQL-python```

from http://codeinthehole.com/writing/how-to-set-up-mysql-for-python-on-ubuntu/

I am now into the data-downloading part and, so far, it is working.

**Comment by palewire** [comment]
Thanks the update. Hmm. I wonder why the ``mysqlclient`` requirement didn't do the job.

**Comment by rkiddy** [comment]
FYI, i was following the instructions at:

http://django-calaccess-raw-data.californiacivicdata.org/en/latest/howtouseit.html

The page mentioned by palewire, http://django-calaccess-raw-data.californiacivicdata.org/en/latest/howtocontribute.html, seems to be similar but not identical to what I am doing. Should the information on these two pages be unified?

**Comment by palewire** [comment]
The first is for people installing the package via PyPI strictly for reuse, the second is for people installing the source code to do development.

**Comment by rkiddy** [comment]
Well, if there is a reason to keep the two procedures separate, they should both probably work.

**Comment by palewire** [comment]
I 100% agree. Do you have happen to have the series of commands you ran in your ``~/.bash_history`` file so I can walk through it myself?

**Comment by palewire** [comment]
I think I've sorted out our disconnect. We do not include the database wrappers in our ``setup.py`` file since the user has the option to choose between MySQL and PostgreSQL. The thinking is that it's silly to force the installation of both requirements, since they're only going to use one. So it's a bit of an extra dependency that is undocumented. It's a hole in our docs and you've found it. I will fix that.

**Comment by palewire** [comment]
I've made an addition to our docs that I hope addresses the issue you raised. Take a look and [let me know](http://django-calaccess-raw-data.californiacivicdata.org/en/latest/howtouseit.html#using-mysql).

**Comment by rkiddy** [comment]
I think the change is not quite enough. Here is what I observed in a new EC2 instance running Ubuntu (64 bit).

```
$ sudo sh
# apt-get update
# apt-get install git
# apt-get install mysql-server
# apt-get install mysql-client
# apt-get install python-pip
# pip install django-calaccess-raw-data
# exit
$ git clone https://github.com/california-civic-data-coalition/django-calaccess-raw-data.git

$ pip install mysqlclient -> ERROR

# pip install mysqlclient -> ERROR

# pip install MySQL-python -> ERROR

# apt-get install libmysqlclient-dev

# pip install mysqlclient -> ERROR

# pip install MySQL-python -> ERROR

# apt-get install python-dev
# pip install mysqlclient
# exit

$ echo "" > ~/.my.cnf
$ echo "[client]" >> ~/.my.cnf
$ echo "password=secret" >> ~/.my.cnf
$ echo "" > ~/.my.cnf
$ echo "create database calaccess;" | mysql -u root
$ vi django-calaccess-raw-data/example/project/settings.py (set the database name and password.)
$ cd django-calaccess-raw-data/example
$ python manage.py migrate
$ python manage.py downloadcalaccessrawdata
```
I must admit I am not expert in using python, in navigating its ecosystem and especially in how some of it is configured. For example, I suspect I do not need to both install the django-calaccess-raw-data app with pip and also to fetch it from the repository. But I tried just installing it and could not find, for example, the settings.py file. From where does one run it?

Anyway. This worked, though the last bit failed because it ran out of space. I had only a micro instance.

**Comment by palewire** [comment]
Thanks for all the great detail. You're right that you only need the pip installation or the source code from Github, not both. 

This is an interesting but tricky question about the proper scope of our documentation. Django, Python and the database backends are heavy duty prerequisites. Each is deeply complex with hundreds of pages of documentation respectively. However, this is true of every other pluggable Django app, not just ours.

In my humble opinion, there's no way we can document how to install and configure all of them here. Especially if we'd need to update our docs each time any of them update.

But I do think we could do a better job explaining the requirements to newbies, and if we link off in a smart way put people on the right path to getting it done. I'll give it a shot, and I'd welcome your input too. 

P.S. We have some early beta versions of a [Django project template](https://github.com/california-civic-data-coalition/django-calaccess-project-template), [Chef cookbook](https://github.com/california-civic-data-coalition/django-calaccess-cookbook) and [Docker hoohah](https://github.com/california-civic-data-coalition/django-calaccess-docker) that bootstrap the whole stack, but there isn't much on any of them so you're likely to run into some bugs there too.

**Comment by palewire** [comment]
Alrighty, I've taken another pass at improving those "how to use it" docs. [Any better?](http://django-calaccess-raw-data.readthedocs.org/en/latest/howtouseit.html)

**Comment by rkiddy** [comment]
This is certainly enough for this issue. I think I will end up writing a "For the django-uninitiated" guide that might be added to your docs. We will see.
