### ISSUE TITLE
Figure out other off_s_h_cd values on ExpnCd model

### ISSUE THREAD

**Issue by aboutaaron** [california-civic-data-coalition/django-calaccess-raw-data#235]
CAL-Access Documentation has this for `off_s_h_cd`:
> Office Sought/Held Code: H=Held; S=Sought

Based on the data, `ExpnCd.objects.values('off_s_h_cd').distinct()` returns the following:

```
[{'off_s_h_cd': u''}, {'off_s_h_cd': u'H'}, {'off_s_h_cd': u'S'}, {'off_s_h_cd': u'A'}, {'off_s_h_cd': u'8'}, {'off_s_h_cd': u'O'}]
```

I'm updating the tuple with these values:

```python
        ('A', 'A - Unknown'),
        ('8', '8 - Unknown'),
        ('O', 'O - Unknown'),
```

Just need to figure out what they represent

**Comment by palewire** [comment]
Here are the frequency of the values in that table

```bash
"S";245262
"s";3040
"O";10
"H";100185
"h";2697
"A";1
"a";1
"8";1
"";4380842
```

They are so uncommon I don't think we need to stress about this ticket, but we should come up with some way of documenting and listing the codes we have failed to define across the whole database.
