### ISSUE TITLE
Figure out other entity_cd values on ExpnCd

### ISSUE THREAD

**Issue by aboutaaron** [california-civic-data-coalition/django-calaccess-raw-data#236]
CAL-Access Documentation has this for `entity_cd`:
> Values: [COM|RCP] - Recipient Committee;
>     IND - Individual;
>     OTH - Other

Based on the data, `ExpnCd.objects.values('entity_cd').distinct()` returns the following:

```
[{'entity_cd': u'OTH'}, {'entity_cd': u''}, {'entity_cd': u'COM'}, {'entity_cd': u'IND'}, {'entity_cd': u'RCP'}, {'entity_cd': u'PTY'}, {'entity_cd': u'SCC'}, {'entity_cd': u'0'}, {'entity_cd': u'BNM'}, {'entity_cd': u'CAO'}, {'entity_cd': u'OFF'}, {'entity_cd': u'PTH'}, {'entity_cd': u'RFD'}, {'entity_cd': u'MBR'}]
```

I'm updating the choices tuple with these values:

```python
        ('PTY', 'PTY - Unknown'),
        ('SCC', 'SCC 0 Unknown'),
        ('BNM', 'BNM - Unknown'),
        ('CAO', 'CAO - Unknown'),
        ('OFF', 'OFF - Unknown'),
        ('PTH', 'PTH - Unknown'),
        ('RFD', 'RFD - Unknown'),
        ('MBR', 'MBR - Unknown'),
        ('0', '0 - Unknown'),
```

Just need to figure out what they represent

**Comment by aboutaaron** [comment]
Possible related to #219

**Comment by rkiddy** [comment]
These are from pages 9 to 11 of the cal_format_201.pdf file which comes with the raw data from the SoS office.

This document specifies what these mean in which forms. Now, verifying that the codes are only used in the correct forms with the expn table is an exercise left for the reader, or to be done later.

```
mysql> select entity_cd, count(*) from expn group by entity_cd order by entity_cd;
+-----------+----------+
| entity_cd | count(*) |
+-----------+----------+
|           |   154777 |
| 0         |       85 |
| BNM       |      975 | -> Ballot Measure's Name/Title
| CAO       |        5 | -> Cand/Officeholder
| COM       |  1397113 | -> Committee
| IND       |   742666 | -> Person (spending > $5000)
| MBR       |        2 | -> Member of Association
| OFF       |       59 | -> Officer
| OTH       |  2175361 | -> Other
| PTH       |        2 | -> perhaps an error (PTY = Party, PTN = Partner)
| PTY       |    19516 | -> Party
| RCP       |    90403 | -> Recipient Committee
| RFD       |        2 | -> a "Type of Payment" = "returned contribution" mistakenly used, see page 13.
| SCC       |      954 | -> Small Contributor Committee
+-----------+----------+
```

**Comment by aboutaaron** [comment]
You're the man Ray. Thanks for this. We should probably have this tuple live somewhere central so we can reference between multiple models. 

-----
Aaron Williams
Journalist/Developer
@aboutaaron




On Fri, Mar 20, 2015 at 5:26 PM -0700, "Ray Kiddy" <notifications@github.com> wrote:












These are from pages 9 to 11 of the cal_format_201.pdf file which comes with the raw data from the SoS office.



This document specifies what these mean in which forms. Now, verifying that the codes are only used in the correct forms with the expn table is an exercise left for the reader, or to be done later.

mysql> select entity_cd, count(*) from expn group by entity_cd order by entity_cd;
+-----------+----------+
| entity_cd | count(*) |
+-----------+----------+
|           |   154777 |
| 0         |       85 |
| BNM       |      975 | -> Ballot Measure's Name/Title
| CAO       |        5 | -> Cand/Officeholder
| COM       |  1397113 | -> Committee
| IND       |   742666 | -> Person (spending > $5000)
| MBR       |        2 | -> Member of Association
| OFF       |       59 | -> Officer
| OTH       |  2175361 | -> Other
| PTH       |        2 | -> perhaps an error (PTY = Party, PTN = Partner)
| PTY       |    19516 | -> Party
| RCP       |    90403 | -> Recipient Committee
| RFD       |        2 | -> a "Type of Payment" = "returned contribution" mistakenly used, see page 13.
| SCC       |      954 | -> Small Contributor Committee
+-----------+----------+
