### ISSUE TITLE
Figure out other juris_cd values on ExpnCd model

### ISSUE THREAD

**Issue by aboutaaron** [california-civic-data-coalition/django-calaccess-raw-data#237]
CAL-Access Documentation has this for `juris_cd`:
> Office Jurisdiction Code Values:
> STW=Statewide;
> SEN=Senate District; ASM=Assembly District;
> BOE=Board of Equalization District;
> CIT=City;
> CTY=County;
> LOC=Local;
>  OTH=Other

Based on the data, `ExpnCd.objects.values('juris_cd').distinct()` returns the following:

```
[{'juris_cd': u''}, {'juris_cd': u'ASM'}, {'juris_cd': u'STW'}, {'juris_cd': u'OTH'}, {'juris_cd': u'SEN'}, {'juris_cd': u'CTY'}, {'juris_cd': u'CIT'}, {'juris_cd': u'BOE'}, {'juris_cd': u'LOC'}, {'juris_cd': u'SEC'}, {'juris_cd': u'O'}, {'juris_cd': u'GEN'}, {'juris_cd': u'STA'}, {'juris_cd': u'GOV'}, {'juris_cd': u'SUP'}, {'juris_cd': u'PDR'}, {'juris_cd': u'CA'}, {'juris_cd': u'(Lo'}, {'juris_cd': u'Ass'}, {'juris_cd': u'(Ci'}, '...(remaining elements truncated)...'] 
```

There are __74__ distinct `juris_cd` values in the ExpnCd table. There is currently no `JURIS_CD_CHOICES` but we should add one once we figure out what to do with these phantom values.

**Comment by palewire** [comment]
Consolidated in #1194
