### ISSUE TITLE
FORM_ID columns in HEADER, RECEIVED_FILINGS and FILER_FILINGS are inconsistently named

### ISSUE THREAD

**Issue by rkiddy** [california-civic-data-coalition/django-calaccess-raw-data#258]
The are 38 tables in the SoS table set that list the form that the data comes from. In 35 of the tables, the column is FORM_TYPE and in 3 of them the column is FORM_ID. This is inconsistent for no reason at all. The FORM_TYPE columns are all VARCHAR2(8) and the 3 FORM_ID columns are VARCHAR2(7).

The columns should be renamed in the model and the import fixed, if there is any issue with it. It will just be easier to work with if this is so. If nobody objects, I can do this at some point. Just checking.

**Comment by palewire** [comment]
Question: Did the state name the fields differently, or is this a variation that we introduced?

**Comment by rkiddy** [comment]
The state named them differently. But that is no reason not to fix them. :-)

**Comment by palewire** [comment]
To me, this is a philosophical software design question. 

I totally agree that it's silly for these fields to have different names. But he scope of this app has been narrowly defined to only be a 1:1 download of the state data, as much as possible. If the state gave them different names, our design dictates ours should have different names. Though we should explain their similarity in our field ``help_text`` and model documentation.

The problem you're pointing out, in my opinion, is best solved in second-layer likes like our campaign-browser, where we make oodles of decisions about how to transform and improve the state's data structure.

**Comment by rkiddy** [comment]
Agreed.
