### ISSUE TITLE
Define link_type values in FilerLinksCd

### ISSUE THREAD

**Issue by rkiddy** [california-civic-data-coalition/django-calaccess-raw-data#259]
It is not obvious what these codes mean and I am unable to find documentation for them.
```
mysql> select LINK_TYPE, count(*) from FILER_LINKS_CD group by LINK_TYPE order by LINK_TYPE;
+-----------+----------+
| LINK_TYPE | count(*) |
+-----------+----------+
|    -12019 |        3 |
|    -12018 |     1108 |
|    -12016 |      802 |
|    -12015 |      111 |
|    -12014 |       16 |
|    -12013 |       12 |
|    -12011 |     2749 |
|    -12008 |     2773 |
|    -12005 |      183 |
|    -12004 |     1019 |
|    -12002 |     4317 |
|    -12001 |    23191 |
|         0 |       29 |
|     12001 |    12111 |
|     12002 |     5068 |
|     12004 |     1790 |
|     12005 |     1277 |
|     12008 |     5383 |
|     12011 |     6369 |
|     12013 |     1362 |
|     12014 |     1995 |
|     12015 |     3413 |
|     12016 |   181564 |
|     12018 |       57 |
|     12019 |        1 |
+-----------+----------+
25 rows in set (0.65 sec)
```

**Comment by palewire** [comment]
This might be something that @armendariz knows.

**Comment by armendariz** [comment]
@palewire @rkiddy I don't it's documented at all.

There's a link type and link description field in that table that may or may not give you more information. I don't have the data loaded up and don't remember. Not do I have the documentation with me right now. I don't remember it being helpful at all.

But I'm pretty sure that table joins up candidates to all of the committees they are associated with. I believe the positive or negative sign denotes something about the direction of the relationship, but I forget.

So you take filter_type_a and plug a candidate it into it, then you should get back a list of recipient committees associated with that candidate id

It probably links lobbyists to their lobbying firms too and other such relationships that exist between filers in the data.

**Comment by rkiddy** [comment]
@palewire @armendariz Of course, I saw that field, but it is not very helpful. In quite a few cases, it is a number. So it seems to be a code for something else.

I think we will probably have to look at filers that are linked, pick a value and figure out what it means. If we have some guessed values, we may be able to get the SoS to explain them more completely.

Augie, I do not think we need to include you in more of the discussion, but thanx for replying. I hear you are in NY. Hope things are good.

**Comment by armendariz** [comment]
@palewire @rkiddy Exactly. I know the table will link candidate ids to all the recipient committee ids that they are associated with. I did that for sure.

But here are some other relationships the table should be able to help with.

Lobbyist employer --> lobbying firms
Lobbying firm --> lobbyists

Ben, sorry if y'all already did all that. I haven't messed around with the code in a while.

Thanks Ray! NY is good but we certainly miss California. Y'all are lucky to live in paradise!

**Comment by palewire** [comment]
It doesn't come close to solving the problem, but I just added all the values found in the database as undefined "choices" the ``link_type`` field on our model.

**Comment by palewire** [comment]
Consolidated in #1194
