### ISSUE TITLE
Can --include options be used in addition to --skip options?

### ISSUE THREAD

**Issue by rkiddy** [california-civic-data-coalition/django-calaccess-raw-data#260]
I often find it simpler to use --include options also. For example, if you want to run steps A through D, one at a time, one can do either:
```
--skip-options b,c,d
--skip-options a,c,d
--skip-options a,b,d
--skip-options a,b,c
```
or one can do:
```
--include-options a
--include-options b
--include-options c
--include-options d
```
Which one is clearer?

**Comment by rkiddy** [comment]
FYI, optparse has now been deprecated and development is going forward with argparse. See: https://docs.python.org/2/library/optparse.html

I may be using argparse to do this.

**Comment by rkiddy** [comment]
It has occurred to me that it would be good to have a separate "importcalaccessrawdata" command. Right now, the download command does not just download. It drives the process. It is convenient, in the browser project, that the "buildcalaccesscampaignbrowser" does not do anything except call the other commands. This makes it very clear and one can see in what order things are happening and so on.

Can I create an import command, have it manage the flags and have it decide what to do and what not to do, and have it call the other commands?

**Comment by palewire** [comment]
Go for it.
