### ISSUE TITLE
upgrading django to 1.8?

### ISSUE THREAD

**Issue by rkiddy** [california-civic-data-coalition/django-calaccess-raw-data#270]
Is there anything to be done here with these projects? Are you all already using 1.8, perhaps with no problems? I am having problems with it, but I did the upgrade without any deliberation and things are horked. It might just be me. Or not. This is a major version upgrade, after all.

FYI, it appears that 1.8 is an LTS release and 1.7 is not.

**Comment by palewire** [comment]
We are already on Django 1.8 so I think that's okay.
