### ISSUE TITLE
Investigate adding delta of downloaded files, not re-creating the whole world every time

### ISSUE THREAD

**Issue by rkiddy** [california-civic-data-coalition/django-calaccess-raw-data#272]
I have started to investigate this and just wanted to let you all know.

Doing a very simple check, looking at a month's data difference, I can see that some files do not get added to at all, many files only get added to, and a fewer number of files have removals and additions.

It seems to me that should simplify the job. If a file only got added to, then only those lines need to be added to the database. Done.

If a file has removals and additions, we can pull out the unique key for the table (usually a set of 3 to 5 of the columns, as one sees in the CalAccessTablesWeb.pdf document supplied by the SoS. The set of removed or added lines is much, much smaller than the number of lines in the file. We can use the unique columns for the table to find the new data and create the update statement for the database.

Let me know if anyone else has suggestions.

**Comment by rkiddy** [comment]
files with no changes in a random 3 week period:

     file: ACRONYMS_CD.TSV, first # 883, second # 883, first only # 0, second only # 0
     file: BALLOT_MEASURES_CD.TSV, first # 109, second # 109, first only # 0, second only # 0
     file: CVR_E530_CD.TSV, first # 190, second # 190, first only # 0, second only # 0
     file: CVR_F470_CD.TSV, first # 0, second # 0, first only # 0, second only # 0
     file: EFS_FILING_LOG_CD.TSV, first # 146813, second # 146813, first only # 0, second only # 0
     file: F495P2_CD.TSV, first # 925, second # 925, first only # 0, second only # 0
     file: FILER_STATUS_TYPES_CD.TSV, first # 8, second # 8, first only # 0, second only # 0
     file: FILER_TYPE_PERIODS_CD.TSV, first # 0, second # 0, first only # 0, second only # 0
     file: FILER_TYPES_CD.TSV, first # 18, second # 18, first only # 0, second only # 0
     file: FILING_PERIOD_CD.TSV, first # 1448, second # 1448, first only # 0, second only # 0
     file: GROUP_TYPES_CD.TSV, first # 20, second # 20, first only # 0, second only # 0
     file: HEADER_CD.TSV, first # 88, second # 88, first only # 0, second only # 0
     file: LEGISLATIVE_SESSIONS_CD.TSV, first # 30, second # 30, first only # 0, second only # 0
     file: LOBBYIST_CONTRIBUTIONS1_CD.TSV, first # 6505, second # 6505, first only # 0, second only # 0
     file: LOBBYIST_CONTRIBUTIONS2_CD.TSV, first # 6505, second # 6505, first only # 0, second only # 0
     file: LOBBYIST_CONTRIBUTIONS3_CD.TSV, first # 6505, second # 6505, first only # 0, second only # 0
     file: LOBBYIST_EMP_LOBBYIST1_CD.TSV, first # 1500, second # 1500, first only # 0, second only # 0
     file: LOBBYIST_EMP_LOBBYIST2_CD.TSV, first # 1500, second # 1500, first only # 0, second only # 0
     file: LOBBYIST_EMPLOYER1_CD.TSV, first # 1730, second # 1730, first only # 0, second only # 0
     file: LOBBYIST_EMPLOYER2_CD.TSV, first # 1730, second # 1730, first only # 0, second only # 0
     file: LOBBYIST_EMPLOYER3_CD.TSV, first # 1730, second # 1730, first only # 0, second only # 0
     file: LOBBYIST_EMPLOYER_FIRMS1_CD.TSV, first # 524, second # 524, first only # 0, second only # 0
     file: LOBBYIST_EMPLOYER_FIRMS2_CD.TSV, first # 524, second # 524, first only # 0, second only # 0
     file: LOBBYIST_EMPLOYER_HISTORY_CD.TSV, first # 0, second # 0, first only # 0, second only # 0
     file: LOBBYIST_FIRM1_CD.TSV, first # 256, second # 256, first only # 0, second only # 0
     file: LOBBYIST_FIRM2_CD.TSV, first # 256, second # 256, first only # 0, second only # 0
     file: LOBBYIST_FIRM3_CD.TSV, first # 256, second # 256, first only # 0, second only # 0
     file: LOBBYIST_FIRM_EMPLOYER1_CD.TSV, first # 170, second # 170, first only # 0, second only # 0
     file: LOBBYIST_FIRM_EMPLOYER2_CD.TSV, first # 170, second # 170, first only # 0, second only # 0
     file: LOBBYIST_FIRM_HISTORY_CD.TSV, first # 0, second # 0, first only # 0, second only # 0
     file: LOBBYIST_FIRM_LOBBYIST1_CD.TSV, first # 577, second # 577, first only # 0, second only # 0
     file: LOBBYIST_FIRM_LOBBYIST2_CD.TSV, first # 577, second # 577, first only # 0, second only # 0
     file: LOOKUP_CODES_CD.TSV, first # 1130, second # 1130, first only # 0, second only # 0

     files with removals and additions:

     file: ADDRESS_CD.TSV, first # 318095, second # 318457, first only # 77, second only # 439
     file: CVR_LOBBY_DISCLOSURE_CD.TSV, first # 266105, second # 266341, first only # 4, second only # 240
     file: CVR_REGISTRATION_CD.TSV, first # 42219, second # 42311, first only # 3, second only # 95
     file: F501_502_CD.TSV, first # 15060, second # 15071, first only # 5, second only # 16
     file: FILER_ADDRESS_CD.TSV, first # 393247, second # 393609, first only # 66, second only # 428
     file: FILER_FILINGS_CD.TSV, first # 1805868, second # 1807106, first only # 3147, second only # 4385
     file: FILER_INTERESTS_CD.TSV, first # 35692, second # 35724, first only # 14, second only # 46
     file: FILER_LINKS_CD.TSV, first # 258237, second # 258500, first only # 140, second only # 403
     file: FILERNAME_CD.TSV, first # 675801, second # 676340, first only # 697, second only # 1213
     file: FILERS_CD.TSV, first # 341158, second # 341424, first only # 11, second only # 277
     file: FILER_TO_FILER_TYPE_CD.TSV, first # 472376, second # 472797, first only # 80, second only # 501
     file: FILER_XREF_CD.TSV, first # 341125, second # 341391, first only # 11, second only # 277
     file: FILINGS_CD.TSV, first # 1679624, second # 1680631, first only # 1, second only # 1008
     file: LOBBYING_CHG_LOG_CD.TSV, first # 56079, second # 56090, first only # 32, second only # 43

     files with only additions:

     file: CVR2_CAMPAIGN_DISCLOSURE_CD.TSV, first # 93743, second # 93837, first only # 0, second only # 94
     file: CVR2_LOBBY_DISCLOSURE_CD.TSV, first # 89612, second # 89719, first only # 0, second only # 107
     file: CVR2_REGISTRATION_CD.TSV, first # 87537, second # 87725, first only # 0, second only # 188
     file: CVR2_SO_CD.TSV, first # 34913, second # 35003, first only # 0, second only # 90
     file: CVR3_VERIFICATION_INFO_CD.TSV, first # 212977, second # 213215, first only # 0, second only # 238
     file: CVR_CAMPAIGN_DISCLOSURE_CD.TSV, first # 333056, second # 333292, first only # 0, second only # 236
     file: CVR_SO_CD.TSV, first # 14020, second # 14051, first only # 0, second only # 31
     file: DEBT_CD.TSV, first # 396120, second # 396514, first only # 0, second only # 394
     file: EXPN_CD.TSV, first # 4618398, second # 4620846, first only # 0, second only # 2448
     file: F690P2_CD.TSV, first # 17215, second # 17248, first only # 0, second only # 33
     file: FILER_ACRONYMS_CD.TSV, first # 1646, second # 1648, first only # 0, second only # 2
     file: FILER_ETHICS_CLASS_CD.TSV, first # 14867, second # 14898, first only # 0, second only # 31
     file: HDR_CD.TSV, first # 647342, second # 647937, first only # 0, second only # 595
     file: IMAGE_LINKS_CD.TSV, first # 14477, second # 14497, first only # 0, second only # 20
     file: LATT_CD.TSV, first # 67848, second # 67852, first only # 0, second only # 4
     file: LCCM_CD.TSV, first # 85429, second # 85461, first only # 0, second only # 32
     file: LEMP_CD.TSV, first # 252917, second # 253516, first only # 0, second only # 599
     file: LEXP_CD.TSV, first # 171341, second # 171438, first only # 0, second only # 97
     file: LOAN_CD.TSV, first # 66343, second # 66364, first only # 0, second only # 21
     file: LOBBY_AMENDMENTS_CD.TSV, first # 10190, second # 10233, first only # 0, second only # 43
     file: LOTH_CD.TSV, first # 12796, second # 12807, first only # 0, second only # 11
     file: LPAY_CD.TSV, first # 418248, second # 418589, first only # 0, second only # 341
     file: NAMES_CD.TSV, first # 428385, second # 428696, first only # 35, second only # 346
     file: RCPT_CD.TSV, first # 8823002, second # 8828261, first only # 0, second only # 5259
     file: RECEIVED_FILINGS_CD.TSV, first # 378879, second # 379084, first only # 0, second only # 205
     file: REPORTS_CD.TSV, first # 38, second # 38, first only # 0, second only # 0
     file: S401_CD.TSV, first # 40865, second # 40872, first only # 0, second only # 7
     file: S496_CD.TSV, first # 34820, second # 34820, first only # 0, second only # 0
     file: S497_CD.TSV, first # 566924, second # 567180, first only # 0, second only # 256
     file: S498_CD.TSV, first # 9178, second # 9180, first only # 0, second only # 2
     file: SMRY_CD.TSV, first # 7612737, second # 7620264, first only # 0, second only # 7527
     file: SPLT_CD.TSV, first # 3060829, second # 3062617, first only # 0, second only # 1788
     file: TEXT_MEMO_CD.TSV, first # 1465967, second # 1469663, first only # 0, second only # 3696

**Comment by palewire** [comment]
What do you think would be the lowest cost way to speeding up the loader by only putting the changes? I know this won't get us every amendment or removals, but couldn't we:

1. Somewhere store the CSV files from the most recent previous downloads
2. Prior to cleaning and loading a CSV file from a new download run a command line [``diff``](http://linux.about.com/library/cmd/blcmdl1_diff.htm) against its companion file in the previous download
3. Only run our existing clean and load commands on files where the computer sees a difference

**Comment by rkiddy** [comment]
That is what I think I have started to do, but I am using the TSV files instead.

I can look at the csv files. It may be better to use the files post-clean.

**Comment by palewire** [comment]
Uh, I hadn't really thought that through. I'm open to using the TSVs. Since the cleans take some time to run it might be even faster to make the yes/no decision before they run.

**Comment by palewire** [comment]
Python [difflib](https://docs.python.org/2/library/difflib.html#module-difflib) seems to be one candidate for making this happen, but I wonder if something else might be faster.
