### ISSUE TITLE
Can dat be integrated into our unittests?

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#281]
- Install dat as part of Travis boot
- Init dat in pre script parts
- Include dat in our test settings files

**Comment by aboutaaron** [comment]
Dat repo: https://github.com/maxogden/dat

**Comment by bcipolli** [comment]
:+1: I'm not familiar with dat, so it's scary making changes and worrying about whether I broke something.

**Comment by aboutaaron** [comment]
This is low priority, but it's a tool @palewire and I have been watching for some time. We just want to get this data in as many places as possible.

**Comment by palewire** [comment]
Consolidated in #1185
