### ISSUE TITLE
empty values on STMNT_STATUS for FilerFilingsCd handled differently in databases?

### ISSUE THREAD

**Issue by dcloud** [california-civic-data-coalition/django-calaccess-raw-data#283]
When running `./manage.py loadcalaccessrawfile -v 3 FilerFilingsCd` against a PostgreSQL database, I noticed that a few entries have no value for STMNT_STATUS in the cvs. If I remove the `NOT NULL` constraint on that column, I can import, with the following result:

```SQL
ccdc> select "STMNT_STATUS", count(*) from "FILER_FILINGS_CD" group by "STMNT_STATUS" order by "STMNT_STATUS" ASC;
+----------------+---------+
|   STMNT_STATUS |   count |
|----------------+---------|
|          11001 | 1325466 |
|          11002 |    2092 |
|          11003 |  492704 |
|         <null> |       2 |
+----------------+---------+
```

This looks similar to what's described in #256, but with NULL rather than 0. I wonder this might be MySQL treating `""` as NULL then coercing NULL values to the default value for that field:

> An attempt to load NULL into a NOT NULL column causes assignment of the implicit default value for the column's data type and a warning, or an error in strict SQL mode

**Comment by dcloud** [comment]
Ah, [here it is](http://dev.mysql.com/doc/refman/5.7/en/problems-with-null.html):

> When reading data with LOAD DATA INFILE, empty or missing columns are updated with ''. To load a NULL value into a column, use \N in the data file. The literal word “NULL” may also be used under some circumstances. See Section 13.2.6, “LOAD DATA INFILE Syntax”.

**Comment by palewire** [comment]
Interesting quirk.  probably don't fully grok the implications, but does this suggest we are improperly saving null values as zeroes and need to add a ``null=True`` to [the field definition](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/models/common.py#L244-L257)?

**Comment by dcloud** [comment]
I'd need to test against MySQL. I set `null=True` on the field definition so that `loadcalaccessrawfile` would work not error out when using PostgreSQL. I don't know that changing the field definition would affect MySQL's behavior for `LOAD DATA INFILE`. Fixing it might require some logic for the MySQL import, assuming we want to adopt NULL as the "correct" value.

**Comment by palewire** [comment]
It's an interesting question. In this case the meaning of an empty string versus a null is unclear -- let alone the meaning of the more common values that truly matter. Perhaps the more prudent approach is convert the field to a ``CharField`` and just load everything as is rather than even try to convert the values to integers at this stage.

**Comment by dcloud** [comment]
If at this "raw" stage we don't know what to expect from various data attributes, it might me better to stick with a charfield. 

Since it looks like this case is a MySQL behavior, I'd be tempted to see what sort of filtering could be done at the python-MySQL level to prevent conversion of empty strings to 0. 

- Daniel Cloud

**Comment by palewire** [comment]
That's a good point. Okay. I think the right call is to change that field to a char, and we should file a new ticket to investigate the MySQL data typing during LOAD DATA INFILE.

**Comment by palewire** [comment]
Consolidated into #1194
