### ISSUE TITLE
Add definitions for the other entity code choices on the RcptCd table

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#55]
Right now we only have

```python
    ENTITY_CODE_CHOICES = (
        ("", "None"),
        ("0", "0"),
        ("BNM", "BNM"),
        ("COM", "Recipient committee"),
        ("IND", "Individual"),
        ("OFF", "OFF"),
        ("OTH", "Other"),
        ("PTY", "Political party"),
        ("RCP", "RCP"),
        ("SCC", "Small contributor committee"),
    )
```

**Comment by rkiddy** [comment]
This seems to be a dupe of another issue: https://github.com/california-civic-data-coalition/django-calaccess-raw-data/issues/236

Or vice versa.

**Comment by palewire** [comment]
Yes, though the entity codes do see to recur on different models. This ticket was intended for the RcptCd contribution schedules from the quarterly filings. The other for the companion expenditure schedules in ExpnCd.

**Comment by palewire** [comment]
Just fixed this thanks to the docs @rkiddy pointed out.
