### ISSUE TITLE
Null timestamps are entered into Postgres as a 1900 date. Can't we put in a null value instead?

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#74]

**Comment by anabranch** [comment]
This was me and was because we didn't have null =true in the models. Can definitely be replaced.


The case statement generation in the data loading will also have to be updated.

Don't think there's anything else that would need to be changed.


—

**Comment by palewire** [comment]
Yep. Shouldn't be a big deal.
