### ISSUE TITLE
Add support for SQLite backend

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#83]

**Comment by hunterowens** [comment]
I'll take it.

**Comment by aboutaaron** [comment]
Can SQLite handle a dataset this large?

**Comment by palewire** [comment]
I don't know! The key thing to know here, @hunterowens, is that we use the bulk CSV loaders ``COPY`` and ``LOAD DATA INFILE`` for PostgreSQL and MySQL, respectively, to jam the data into the database. 

You can find all that code in [this management command](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/management/commands/loadcalaccessrawfile.py). And if you stick with our current idiom you'd need to introduce some third branch there for SQLite backends that takes a CSV and jams it into the database, with the date formatting transformation the trickiest prepreprocessing step.

**Comment by aboutaaron** [comment]
This also may be of help: https://github.com/rgrp/csv2sqlite

**Comment by hunterowens** [comment]
@aboutaaron I've used sqlite dbs that are north of 2 gb, so I think sizing should be fine. Performance is good as long as you have a lot of memory on your cpu. 

I can also I assume use the `sqlite> .import <filename> <tablename>`, which is equivalent to `COPY` in postgres land.

**Comment by palewire** [comment]
Sounds good. The main thing to watch out for is if your datetime fields are landing propertly. The format in the state CSV is unconventional.

**Comment by hunterowens** [comment]
Got it. Where is the default data dir anyways?

**Comment by anabranch** [comment]
Data is downloaded into the 'data' directory. You have to run the first management command to download all the data before you can start this process. 

`python manage.py downloadcalaccessrawdata' should get you all the data in a 'data' directory in that example folder.

**Comment by palewire** [comment]
And you can always override it with our [custom setting](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/blob/master/calaccess_raw/__init__.py#L7) if you want.

**Comment by hunterowens** [comment]
Cool thanks! Is this `"1/1/2001 12:00:00 AM"` the timestamp format that you are referencing?

**Comment by palewire** [comment]
Yes. And some are date only.

**Comment by hunterowens** [comment]
Got it. Thoughts about introducing csvkit as a dependency? The parser is way better than the built in .import provided by sqlite. (For example, .import will treat "some_field" as "some_field" to import into the db, rather than dropping the quotes.

**Comment by hunterowens** [comment]
It also handles the datetime objects correctly in sqllite.

**Comment by palewire** [comment]
Our original loader used it for that purpose, but it added several hours to the routine because the files as so large. What you see now is the reflection of an effort to strip off chrome for speed.

**Comment by hunterowens** [comment]
Got it. `.import` is pretty much slower than csvkit in my experience for sqlite, so I'm going to just use `CSVReader` (uhh) and generate line by line insert statements? 

That doesn't seem super non-hacky, but it might work.

**Comment by palewire** [comment]
It never hurts to try. But if there's any bulk loader ala ``COPY`` available it's worth comparing performance.

**Comment by anabranch** [comment]
Line by line (at least with Postgres) was prohibitively slow especially when the files get larger. 



Bill Chambers
President - Information Management Student Association

UC Berkeley School of Information
Cell: 415-310-2314


http://billchambers.me/

Email | LinkedIn | Twitter | Github

**Comment by hunterowens** [comment]
`.import` is the bulk loader. I'm going to try and get it to play nicely.

**Comment by hunterowens** [comment]
Problem with it is that you have to update the tables after load, with NULL being replaced by null, and datetime parsing. Which is time intensive. 

[background](http://cs.stanford.edu/people/widom/cs145/sqlite/SQLiteLoad.html)

**Comment by hunterowens** [comment]
Basically, the bulk loader allows no parsing. Therefore, the statements that use `COPY` and `LOAD_DATA_INFILE` into temp_taple are going to be faster than anything using .import because I think I'll have to post-process either line-by-line or column-by-column.  The alternative is to to preprocess the csv, but at that point, why not just use csvkit? 

hmm. I'll let you know if I come up with anything better.

**Comment by palewire** [comment]
Welcome to our special hell. Good luck! There's a prize waiting!

**Comment by anabranch** [comment]
@palewire too true. It's just like postgresql....

Hunter a logged a lot of my challenges when setting up postgresql on my website - it might help you avoid some of the obvious issues.
http://billchambers.me/projects/2014/11/25/civic-data-postgresql-support.html

**Comment by hunterowens** [comment]
That MSSQL ticket is going to be open forever. And @anabranch, thanks for the link. I'm testing out a few different solutions. How long does it take y'all to load on the supported backends?

**Comment by anabranch** [comment]
Can't quite remember, I believe some of them can take several minutes. I believe it's quadratic in speed at which it loads, anything under a couple hundred megs was decent (~sub 1 minute) while something like rcpt would take 5 to 10.

Take those numbers with a grain of salt though, those are not measurements by any means - more of just what I more or less remember how long it was taking.

It might be nice to have some benchmarks recorded somewhere so that we could better understand our optimizations/which one is fastest/which one is easiest.

**Comment by hunterowens** [comment]
Okay, so the best solution appears to be the `c.executemany()` in sqlite3. Trying to implement the date parsing now.

**Comment by hunterowens** [comment]
Ok. I did executemany() and the performance left a lot to be desired (took 6 hours on my Macbook Pro Retina 8GB ram). If the desire of having sqlite support is because there are many more environments where it exists and no installing problems, the performance issues would probably be a huge hit. 

Recommend closing.

**Comment by palewire** [comment]
Thanks for doing this valuable research. I wonder if a sqlite proponent like @dwillis might know any bulk loading tricks we do not.

**Comment by hunterowens** [comment]
I suspect their could be a way to optimize the loading, but that would require DB schema changes. I'll let @dwills chime in, but this might just be too big for sqlite.

**Comment by palewire** [comment]
I don't like the idea of changing the data schema. The goal of this app is to represent the raw data as provided by the state. 

I also wonder if even a slow loader might be worth including anyway. It could be optimized in the future, and still provide a new option we don't currently support.

**Comment by hunterowens** [comment]
Okay, will try and whip up a PR next week.

**Comment by dwillis** [comment]
I'm not aware of any bulk loading tricks, and it seems like this particular data would need to be handled row-by-row for variations in dates.
