### ISSUE TITLE
Create a management command or other method for automating database dump archives

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#85]

**Comment by allanjamesvestal** [comment]
Looking into this.

Would it be a more sophisticated, project specific form of ```dumpdata```?

**Comment by allanjamesvestal** [comment]
I'll get this.

This might be the key: [https://github.com/vitaliyf/django-dbdump](https://github.com/vitaliyf/django-dbdump).

I'll have to see if it's still good with Django 1.7+ (and Python 3), but if it is, I'd just strip out the auth app (and maybe other django.contrib apps too) and throw the resulting dump into a time-stamped file.

If the library isn't compatible, I'll fork the django-dbdump package and submit a request to that.

As time permits, I'll add an option for backup destination &mdash; so someone could specify whether they wanted the backup to be stored locally or on some service like S3 or Glacier.

**Comment by palewire** [comment]
As I reflect more on this patch, I am leaning towards leaving the backup decision to people who are implementing this app in individual projects.
