### ISSUE TITLE
Clean "choices" tuple for the values in CvrSoCd model's form_type field

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-raw-data#86]

**Comment by JoeGermuska** [comment]
it bugged me that one of these was unclosed, but I don't understand how this relates to #87 except that the schema are clearly different and CVR_SO_CD has form 402 rows while CVR2_SO_CD doesn't, even though [it's listed in the choices](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/commit/446fe40ce94a8a57bf4318fe6216624a0fd91871)

**Comment by palewire** [comment]
There are two different components of a Statement of Organization form, I think. 

Here are group and counts on those fields for the two tables for our comparison.

```sql
SELECT form_type, COUNT(*)
FROM CVR_SO_CD
GROUP BY 1
ORDER BY 1;
```
|form_type|count|
|-------------|--------|
|'F400'|114|
|'F402|40|
|'F410'|13224|

```sql
SELECT form_type, COUNT(*)
FROM CVR2_SO_CD
GROUP BY 1
ORDER BY 1;
```

|form_type|count|
|-------------|--------|
|'F400'|369|
|'F410'|32755|

This is going to get really boring really fast, but when I refer back to the forms I see that only the F400 (Slate mailer committee creation) and the F410 (Recipient committee creation) include a second page. The F402 (Slate mailer termination) is a single pager.

**400**

![alt text](https://s3.amazonaws.com/s3.documentcloud.org/documents/1308004/pages/cal-access-forms-p6-normal.gif)
![alt text](https://s3.amazonaws.com/s3.documentcloud.org/documents/1308004/pages/cal-access-forms-p7-normal.gif)

**402**

![402](https://s3.amazonaws.com/s3.documentcloud.org/documents/1308004/pages/cal-access-forms-p22-normal.gif)

**410**

![410](https://s3.amazonaws.com/s3.documentcloud.org/documents/1308004/pages/cal-access-forms-p26-normal.gif)
![410](https://s3.amazonaws.com/s3.documentcloud.org/documents/1308004/pages/cal-access-forms-p26-normal.gif)

That explains why we see all three form types in the first table, but only two in the second table.
