### ISSUE TITLE
Windows requirements installation bug

### ISSUE THREAD

**Issue by karkinosw** [california-civic-data-coalition/django-calaccess-raw-data#996]
Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\users\carlos wehner\envs\
django-calaccess-raw-data\lib\site-packages (from hurry.filesize->-r requirements_dev.txt (line 5))
Collecting sh (from python-coveralls->-r requirements_dev.txt (line 8))
  Downloading sh-1.11.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\carlos~1\appdata\local\temp\pip-build-7eokmd\sh\setup.py", line 4, in <module>
        import sh
      File "sh.py", line 37, in <module>
        support." % __version__)
    ImportError: sh 1.11 is currently only supported on linux and osx. please install pbs 0.110 (htt
p://pypi.python.org/pypi/pbs) for windows support.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\carlos~1\appdata\local\temp\
pip-build-7eokmd\sh

**Comment by palewire** [comment]
Considering all the refactoring we've had in recent months, this bug is far behind our master branch and will be closed barring it coming up again for users. If it does, we'll approach it again then.
